# APRS symbol lookup. Each entry maps (table_id, symbol_code) → (description, station_type).
#
# table_id is the symbol table identifier character:
#   '/' = Primary table
#   '\' = Alternate table
#   Any other char = overlay (treated as alternate table)
#
# station_type values: mobile, fixed, weather, emergency, infrastructure, aircraft, marine, unknown

_SYMBOLS: dict[tuple[str, str], tuple[str, str]] = {
    # Primary table '/'
    ("/", "!"): ("Police Station", "fixed"),
    ("/", '"'): ("No Entry", "fixed"),
    ("/", "#"): ("Digi / Gateway", "infrastructure"),
    ("/", "$"): ("Phone", "fixed"),
    ("/", "%"): ("DX Cluster", "infrastructure"),
    ("/", "&"): ("HF Gateway", "infrastructure"),
    ("/", "'"): ("Small Aircraft", "aircraft"),
    ("/", "("): ("Mobile Satellite Station", "infrastructure"),
    ("/", ")"): ("Wheelchair", "fixed"),
    ("/", "*"): ("Snowflake / Snow", "weather"),
    ("/", "+"): ("Cross / Aid Station", "emergency"),
    ("/", ","): ("Store", "fixed"),
    ("/", "-"): ("House", "fixed"),
    ("/", "."): ("X / Unknown Position", "unknown"),
    ("/", "/"): ("Dot", "unknown"),
    ("/", "0"): ("Circle (0)", "unknown"),
    ("/", "1"): ("Circle (1)", "unknown"),
    ("/", "2"): ("Circle (2)", "unknown"),
    ("/", "3"): ("Circle (3)", "unknown"),
    ("/", "4"): ("Circle (4)", "unknown"),
    ("/", "5"): ("Circle (5)", "unknown"),
    ("/", "6"): ("Circle (6)", "unknown"),
    ("/", "7"): ("Circle (7)", "unknown"),
    ("/", "8"): ("Circle (8)", "unknown"),
    ("/", "9"): ("Circle (9)", "unknown"),
    ("/", ":"): ("Fire", "emergency"),
    ("/", ";"): ("Campground / Tent", "fixed"),
    ("/", "<"): ("Motorcycle", "mobile"),
    ("/", "="): ("Railroad Engine", "mobile"),
    ("/", ">"): ("Car", "mobile"),
    ("/", "?"): ("File Server", "infrastructure"),
    ("/", "@"): ("Hurricane / Tropical Storm", "weather"),
    ("/", "A"): ("Aid Station", "emergency"),
    ("/", "B"): ("BBS", "infrastructure"),
    ("/", "C"): ("Canoe", "marine"),
    ("/", "D"): ("", "unknown"),
    ("/", "E"): ("Eyeball", "fixed"),
    ("/", "F"): ("Tractor / Farm", "mobile"),
    ("/", "G"): ("Grid Square (3x3)", "fixed"),
    ("/", "H"): ("Hotel", "fixed"),
    ("/", "I"): ("TCP/IP Network Node", "infrastructure"),
    ("/", "J"): ("", "unknown"),
    ("/", "K"): ("School", "fixed"),
    ("/", "L"): ("PC User", "fixed"),
    ("/", "M"): ("Mac", "fixed"),
    ("/", "N"): ("NTS Station", "fixed"),
    ("/", "O"): ("Balloon", "aircraft"),
    ("/", "P"): ("Police Car", "emergency"),
    ("/", "Q"): ("", "unknown"),
    ("/", "R"): ("RV / Recreational Vehicle", "mobile"),
    ("/", "S"): ("Space Shuttle", "aircraft"),
    ("/", "T"): ("SSTV", "fixed"),
    ("/", "U"): ("Bus", "mobile"),
    ("/", "V"): ("ATV", "mobile"),
    ("/", "W"): ("National WX Service Site", "weather"),
    ("/", "X"): ("Helicopter", "aircraft"),
    ("/", "Y"): ("Yacht / Sailboat", "marine"),
    ("/", "Z"): ("WinAPRS", "infrastructure"),
    ("/", "["): ("Jogger / Person", "mobile"),
    ("/", "\\"): ("Triangle", "unknown"),
    ("/", "]"): ("PBBS", "infrastructure"),
    ("/", "^"): ("Large Aircraft", "aircraft"),
    ("/", "_"): ("Weather Station", "weather"),
    ("/", "`"): ("Dish Antenna", "infrastructure"),
    ("/", "a"): ("Ambulance", "emergency"),
    ("/", "b"): ("Bike / Bicycle", "mobile"),
    ("/", "c"): ("Incident Command Post", "emergency"),
    ("/", "d"): ("Fire Dept", "emergency"),
    ("/", "e"): ("Horse (Equestrian)", "mobile"),
    ("/", "f"): ("Fire Truck", "emergency"),
    ("/", "g"): ("Glider", "aircraft"),
    ("/", "h"): ("Hospital", "emergency"),
    ("/", "i"): ("IOTA (Islands on the Air)", "fixed"),
    ("/", "j"): ("Jeep", "mobile"),
    ("/", "k"): ("Truck", "mobile"),
    ("/", "l"): ("Laptop", "fixed"),
    ("/", "m"): ("Mic-E Repeater", "infrastructure"),
    ("/", "n"): ("Node", "infrastructure"),
    ("/", "o"): ("EOC / Emergency Ops", "emergency"),
    ("/", "p"): ("Rover / Dog", "mobile"),
    ("/", "q"): ("Grid Square", "fixed"),
    ("/", "r"): ("Antenna / Repeater", "infrastructure"),
    ("/", "s"): ("Power Boat / Ship", "marine"),
    ("/", "t"): ("Truck Stop", "fixed"),
    ("/", "u"): ("Semi Truck / 18-Wheeler", "mobile"),
    ("/", "v"): ("Van", "mobile"),
    ("/", "w"): ("Water Station", "fixed"),
    ("/", "x"): ("X / APRS Software", "infrastructure"),
    ("/", "y"): ("Yagi Antenna", "infrastructure"),
    ("/", "z"): ("Shelter", "fixed"),
    # Alternate table '\'
    ("\\", "#"): ("Overlay Digi", "infrastructure"),
    ("\\", "$"): ("Bank / ATM", "fixed"),
    ("\\", "&"): ("Gateway / Internet", "infrastructure"),
    ("\\", "'"): ("Crash / Incident Site", "emergency"),
    ("\\", "("): ("Cloudy", "weather"),
    ("\\", "*"): ("Snow", "weather"),
    ("\\", "+"): ("Church", "fixed"),
    ("\\", "-"): ("House (HF)", "fixed"),
    ("\\", "."): ("Ambiguous / Waypoint", "unknown"),
    ("\\", ";"): ("Park / Picnic", "fixed"),
    ("\\", "<"): ("Advisory", "weather"),
    ("\\", ">"): ("Car (Varicolor)", "mobile"),
    ("\\", "@"): ("Storm", "weather"),
    ("\\", "A"): ("Box", "fixed"),
    ("\\", "D"): ("Drizzle", "weather"),
    ("\\", "E"): ("Smoke", "weather"),
    ("\\", "F"): ("Freeze Warning", "weather"),
    ("\\", "G"): ("Snow Shower", "weather"),
    ("\\", "H"): ("Haze", "weather"),
    ("\\", "I"): ("Rain Shower", "weather"),
    ("\\", "J"): ("Lightning", "weather"),
    ("\\", "K"): ("Kenwood", "fixed"),
    ("\\", "N"): ("Navigation Buoy", "marine"),
    ("\\", "O"): ("Rocket", "aircraft"),
    ("\\", "P"): ("Parking", "fixed"),
    ("\\", "Q"): ("Earthquake", "fixed"),
    ("\\", "R"): ("Restaurant", "fixed"),
    ("\\", "S"): ("Satellite", "aircraft"),
    ("\\", "T"): ("Thunderstorm", "weather"),
    ("\\", "U"): ("Sunny", "weather"),
    ("\\", "V"): ("VORTAC / Nav Aid", "infrastructure"),
    ("\\", "W"): ("NWS Site (Varicolor)", "weather"),
    ("\\", "X"): ("Pharmacy / Drug Store", "fixed"),
    ("\\", "Y"): ("Radiosonde / Sonde", "aircraft"),
    ("\\", "["): ("Wall Cloud", "weather"),
    ("\\", "^"): ("Aircraft (Varicolor)", "aircraft"),
    ("\\", "_"): ("Weather Station (Varicolor)", "weather"),
    ("\\", "a"): ("Fog", "weather"),
    ("\\", "f"): ("Funnel Cloud / Tornado", "weather"),
    ("\\", "g"): ("Gale", "weather"),
    ("\\", "h"): ("HAM Store", "fixed"),
    ("\\", "k"): ("4x4 / Off Road", "mobile"),
    ("\\", "m"): ("Milepost", "fixed"),
    ("\\", "n"): ("Triangle (NDB)", "infrastructure"),
    ("\\", "o"): ("Small Circle", "unknown"),
    ("\\", "p"): ("Partly Cloudy", "weather"),
    ("\\", "r"): ("Restrooms", "fixed"),
    ("\\", "s"): ("Boat (Varicolor)", "marine"),
    ("\\", "t"): ("Tornado", "weather"),
    ("\\", "u"): ("Truck (Varicolor)", "mobile"),
    ("\\", "v"): ("Van (Varicolor)", "mobile"),
    ("\\", "w"): ("Flooding", "weather"),
    ("\\", "y"): ("Skywarn", "weather"),
    ("\\", "z"): ("Shelter (Varicolor)", "fixed"),
}

_STATION_TYPE_LABELS: dict[str, str] = {
    "mobile": "Mobile",
    "fixed": "Fixed",
    "weather": "Weather",
    "emergency": "Emergency",
    "infrastructure": "Infrastructure",
    "aircraft": "Aircraft",
    "marine": "Marine",
    "unknown": "Unknown",
}


def classify_symbol(table_id: str, symbol_code: str) -> tuple[str, str]:
    """Return (description, station_type) for an APRS symbol.

    Falls back to overlay handling for non-standard table IDs.
    """
    key = (table_id, symbol_code)
    if key in _SYMBOLS:
        return _SYMBOLS[key]
    # Non-standard table IDs are overlays — treat as alternate table
    alt_key = ("\\", symbol_code)
    if alt_key in _SYMBOLS:
        desc, stype = _SYMBOLS[alt_key]
        return desc, stype
    return "", "unknown"
